apiVersion: v1
kind: Service
metadata:
  name: front-expose-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001  # It is exposed port
    protocol: TCP
  selector:
    app: psi-front
