spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    username: username
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /api/v1

mail:
  mailjet:
    apiKey: "bc910b4624a20dd8d617d2fc5dbe98c6"
    apiSecret: "2b28ad5c16d1e677c095019c603a263a"
    version: "v3.1"
    senderMail: "marcel.k@onet.eu"
    senderName: "Politechnika Wrocławska"
    mailSubject: "Praca dyplomowa - powiadomienie"